### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by jbrucker** [pknn1/ske-restaurant#3]
Did you test your code?
I got this:
```
What do you want to do?
(o)rder, (c)heck order, check ou(t): o
 1. Cheese Pizza         -- 220.00 Baht
 2. Pizza with mushroom  -- 250.00 Baht
 3. Salad, small         -- 30.00 Baht
 4. Ice Tea              -- 20.00 Baht
How to order: (menu name / code)(/)(quantity)
What do you want to order: 2
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at RestaurantManager.orderFood(Unknown Source)
	at SKERestaurant.openSKERestaurant(Unknown Source)
	at SKERestaurant.main(Unknown Source)

```

**Comment by pknn1** [comment]
Order form is : menucode/quantity
